[2024-01-04T20:00:59.982+0000] {processor.py:161} INFO - Started process (PID=972) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:00:59.984+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:00:59.987+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:00:59.985+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:01:00.476+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:01:00.072+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 12, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:01:00.541+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:01:00.679+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.703 seconds
[2024-01-04T20:01:31.319+0000] {processor.py:161} INFO - Started process (PID=1029) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:01:31.321+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:01:31.323+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:01:31.322+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:01:31.362+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:01:31.357+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 12, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:01:31.364+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:01:31.400+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.085 seconds
[2024-01-04T20:02:01.517+0000] {processor.py:161} INFO - Started process (PID=1086) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:02:01.518+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:02:01.519+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:02:01.519+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:02:01.544+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:02:01.539+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 12, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:02:01.545+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:02:01.575+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.062 seconds
[2024-01-04T20:02:31.951+0000] {processor.py:161} INFO - Started process (PID=1143) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:02:31.952+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:02:31.954+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:02:31.954+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:02:31.987+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:02:31.978+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 12, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:02:31.989+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:02:32.016+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.070 seconds
[2024-01-04T20:03:02.093+0000] {processor.py:161} INFO - Started process (PID=1200) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:03:02.095+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:03:02.096+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:03:02.096+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:03:02.137+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:03:02.129+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 12, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:03:02.139+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:03:02.171+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.082 seconds
[2024-01-04T20:03:32.471+0000] {processor.py:161} INFO - Started process (PID=1257) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:03:32.472+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:03:32.473+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:03:32.473+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:03:32.504+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:03:32.497+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 12, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:03:32.506+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:03:32.534+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.067 seconds
[2024-01-04T20:04:02.705+0000] {processor.py:161} INFO - Started process (PID=1314) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:04:02.706+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:04:02.707+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:04:02.707+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:04:02.732+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:04:02.727+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 12, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:04:02.734+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:04:02.763+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.062 seconds
[2024-01-04T20:04:32.898+0000] {processor.py:161} INFO - Started process (PID=1371) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:04:32.900+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:04:32.902+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:04:32.901+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:04:32.936+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:04:32.927+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 12, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:04:32.939+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:04:32.969+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.076 seconds
[2024-01-04T20:05:03.276+0000] {processor.py:161} INFO - Started process (PID=1428) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:05:03.282+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:05:03.283+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:05:03.283+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:05:03.307+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:05:03.302+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 12, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:05:03.309+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:05:03.340+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.067 seconds
[2024-01-04T20:05:33.912+0000] {processor.py:161} INFO - Started process (PID=1485) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:05:33.914+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:05:33.915+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:05:33.915+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:05:33.941+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:05:33.934+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 12, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:05:33.944+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:05:33.974+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.066 seconds
[2024-01-04T20:06:04.184+0000] {processor.py:161} INFO - Started process (PID=1542) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:06:04.186+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:06:04.187+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:06:04.187+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:06:04.218+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:06:04.211+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 12, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:06:04.220+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:06:04.247+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.067 seconds
[2024-01-04T20:06:34.536+0000] {processor.py:161} INFO - Started process (PID=1599) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:06:34.538+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:06:34.540+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:06:34.539+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:06:34.588+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:06:34.578+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 12, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:06:34.592+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:06:34.650+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.120 seconds
[2024-01-04T20:07:04.773+0000] {processor.py:161} INFO - Started process (PID=1656) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:07:04.775+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:07:04.776+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:07:04.775+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:07:04.803+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:07:04.797+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 12, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:07:04.805+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:07:04.831+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.061 seconds
[2024-01-04T20:07:34.997+0000] {processor.py:161} INFO - Started process (PID=1713) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:07:34.998+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:07:35.001+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:07:35.000+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:07:35.050+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:07:35.040+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 12, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:07:35.053+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:07:35.082+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.091 seconds
[2024-01-04T20:08:05.126+0000] {processor.py:161} INFO - Started process (PID=1770) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:08:05.127+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:08:05.128+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:08:05.128+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:08:05.150+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:08:05.146+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 12, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:08:05.152+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:08:05.173+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.050 seconds
[2024-01-04T20:08:35.579+0000] {processor.py:161} INFO - Started process (PID=1827) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:08:35.580+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:08:35.582+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:08:35.581+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:08:35.616+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:08:35.608+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 12, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:08:35.618+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:08:35.643+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.069 seconds
[2024-01-04T20:09:05.900+0000] {processor.py:161} INFO - Started process (PID=1884) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:09:05.901+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:09:05.902+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:09:05.902+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:09:05.936+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:09:05.928+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 12, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:09:05.939+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:09:05.972+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.077 seconds
[2024-01-04T20:09:36.695+0000] {processor.py:161} INFO - Started process (PID=1941) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:09:36.709+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:09:36.715+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:09:36.713+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:09:36.744+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:09:36.739+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 12, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:09:36.746+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:09:36.779+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.089 seconds
[2024-01-04T20:10:06.866+0000] {processor.py:161} INFO - Started process (PID=1997) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:10:06.868+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:10:06.870+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:10:06.870+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:10:06.899+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:10:06.894+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 12, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:10:06.901+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:10:06.929+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.067 seconds
[2024-01-04T20:10:37.063+0000] {processor.py:161} INFO - Started process (PID=2053) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:10:37.064+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:10:37.065+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:10:37.065+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:10:37.094+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:10:37.088+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 12, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:10:37.096+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:10:37.125+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.067 seconds
[2024-01-04T20:11:07.251+0000] {processor.py:161} INFO - Started process (PID=2110) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:11:07.253+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:11:07.254+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:11:07.254+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:11:07.287+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:11:07.281+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 12, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:11:07.289+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:11:07.331+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.085 seconds
[2024-01-04T20:11:37.566+0000] {processor.py:161} INFO - Started process (PID=2167) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:11:37.567+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:11:37.568+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:11:37.568+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:11:37.594+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:11:37.588+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 12, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:11:37.596+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:11:37.619+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.058 seconds
[2024-01-04T20:12:08.112+0000] {processor.py:161} INFO - Started process (PID=2224) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:12:08.114+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:12:08.115+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:12:08.115+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:12:08.154+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:12:08.147+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 12, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:12:08.157+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:12:08.181+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.072 seconds
[2024-01-04T20:12:38.317+0000] {processor.py:161} INFO - Started process (PID=2275) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:12:38.318+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:12:38.319+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:12:38.319+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:12:38.345+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:12:38.339+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 12, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:12:38.347+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:12:38.370+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.058 seconds
[2024-01-04T20:13:08.666+0000] {processor.py:161} INFO - Started process (PID=2332) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:13:08.668+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:13:08.670+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:13:08.670+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:13:08.700+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:13:08.694+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 12, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:13:08.703+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:13:08.727+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.073 seconds
[2024-01-04T20:13:39.172+0000] {processor.py:161} INFO - Started process (PID=2389) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:13:39.173+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:13:39.175+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:13:39.174+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:13:39.206+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:13:39.197+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 12, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:13:39.208+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:13:39.231+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.062 seconds
[2024-01-04T20:14:09.771+0000] {processor.py:161} INFO - Started process (PID=2446) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:14:09.773+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:14:09.775+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:14:09.774+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:14:09.818+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:14:09.812+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 12, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:14:09.819+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:14:09.846+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.080 seconds
[2024-01-04T20:14:40.019+0000] {processor.py:161} INFO - Started process (PID=2503) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:14:40.020+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:14:40.022+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:14:40.022+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:14:40.054+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:14:40.048+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 12, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:14:40.056+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:14:40.089+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.075 seconds
[2024-01-04T20:15:10.637+0000] {processor.py:161} INFO - Started process (PID=2560) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:15:10.640+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:15:10.642+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:15:10.642+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:15:10.678+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:15:10.670+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 12, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:15:10.681+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:15:10.718+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.089 seconds
[2024-01-04T20:15:41.238+0000] {processor.py:161} INFO - Started process (PID=2617) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:15:41.239+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:15:41.241+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:15:41.241+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:15:41.277+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:15:41.270+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 12, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:15:41.280+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:15:41.309+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.076 seconds
[2024-01-04T20:16:11.590+0000] {processor.py:161} INFO - Started process (PID=2675) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:16:11.592+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:16:11.596+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:16:11.595+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:16:11.663+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:16:11.651+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 12, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:16:11.666+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:16:11.719+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.135 seconds
[2024-01-04T20:16:42.306+0000] {processor.py:161} INFO - Started process (PID=2732) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:16:42.308+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:16:42.314+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:16:42.313+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:16:42.348+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:16:42.340+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 12, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:16:42.351+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:16:42.380+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.078 seconds
[2024-01-04T20:17:12.700+0000] {processor.py:161} INFO - Started process (PID=2789) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:17:12.701+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:17:12.702+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:17:12.702+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:17:12.749+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:17:12.743+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 12, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:17:12.752+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:17:12.816+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.121 seconds
[2024-01-04T20:17:43.031+0000] {processor.py:161} INFO - Started process (PID=2846) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:17:43.034+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:17:43.036+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:17:43.035+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:17:43.064+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:17:43.057+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 12, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:17:43.067+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:17:43.115+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.089 seconds
[2024-01-04T20:18:13.281+0000] {processor.py:161} INFO - Started process (PID=2903) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:18:13.283+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:18:13.285+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:18:13.285+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:18:13.317+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:18:13.310+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 12, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:18:13.320+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:18:13.349+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.074 seconds
[2024-01-04T20:18:44.087+0000] {processor.py:161} INFO - Started process (PID=2961) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:18:44.088+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:18:44.090+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:18:44.089+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:18:44.125+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:18:44.118+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 12, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:18:44.127+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:18:44.160+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.078 seconds
[2024-01-04T20:19:15.216+0000] {processor.py:161} INFO - Started process (PID=3018) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:19:15.218+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:19:15.221+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:19:15.220+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:19:15.270+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:19:15.261+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 12, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:19:15.272+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:19:15.296+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.087 seconds
[2024-01-04T20:19:45.507+0000] {processor.py:161} INFO - Started process (PID=3075) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:19:45.510+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:19:45.512+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:19:45.512+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:19:45.544+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:19:45.538+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 12, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:19:45.547+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:19:45.580+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.080 seconds
[2024-01-04T20:20:16.059+0000] {processor.py:161} INFO - Started process (PID=3132) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:20:16.060+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:20:16.061+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:20:16.061+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:20:16.089+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:20:16.083+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 12, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:20:16.091+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:20:16.114+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.059 seconds
[2024-01-04T20:20:46.254+0000] {processor.py:161} INFO - Started process (PID=3189) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:20:46.255+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:20:46.257+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:20:46.256+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:20:46.301+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:20:46.294+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 12, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:20:46.304+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:20:46.331+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.083 seconds
[2024-01-04T20:21:16.646+0000] {processor.py:161} INFO - Started process (PID=3246) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:21:16.648+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:21:16.650+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:21:16.649+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:21:16.688+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:21:16.679+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 12, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:21:16.691+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:21:16.716+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.073 seconds
[2024-01-04T20:21:22.450+0000] {processor.py:161} INFO - Started process (PID=3270) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:21:22.452+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:21:22.454+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:21:22.453+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:21:22.510+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:21:22.502+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:21:22.513+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:21:22.544+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.100 seconds
[2024-01-04T20:21:54.491+0000] {processor.py:161} INFO - Started process (PID=3320) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:21:54.514+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:21:54.518+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:21:54.517+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:21:54.590+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:21:54.582+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:21:54.594+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:21:54.718+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.232 seconds
[2024-01-04T20:22:25.307+0000] {processor.py:161} INFO - Started process (PID=3378) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:22:25.309+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:22:25.311+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:22:25.310+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:22:25.352+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:22:25.346+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:22:25.354+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:22:25.384+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.082 seconds
[2024-01-04T20:22:55.633+0000] {processor.py:161} INFO - Started process (PID=3435) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:22:55.636+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:22:55.637+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:22:55.637+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:22:55.669+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:22:55.662+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:22:55.672+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:22:55.706+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.078 seconds
[2024-01-04T20:22:59.398+0000] {processor.py:161} INFO - Started process (PID=3449) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:22:59.399+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:22:59.400+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:22:59.400+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:22:59.447+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:22:59.439+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:22:59.449+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:22:59.489+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.098 seconds
[2024-01-04T20:23:29.802+0000] {processor.py:161} INFO - Started process (PID=3506) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:23:29.804+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:23:29.805+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:23:29.805+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:23:29.831+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:23:29.826+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:23:29.833+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:23:29.862+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.064 seconds
[2024-01-04T20:24:00.151+0000] {processor.py:161} INFO - Started process (PID=3563) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:24:00.152+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:24:00.154+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:24:00.153+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:24:00.182+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:24:00.176+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:24:00.184+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:24:00.211+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.064 seconds
[2024-01-04T20:24:30.297+0000] {processor.py:161} INFO - Started process (PID=3619) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:24:30.298+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:24:30.300+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:24:30.299+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:24:30.342+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:24:30.333+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:24:30.344+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:24:30.369+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.076 seconds
[2024-01-04T20:25:00.507+0000] {processor.py:161} INFO - Started process (PID=3676) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:25:00.509+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:25:00.510+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:25:00.510+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:25:00.545+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:25:00.537+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:25:00.548+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:25:00.576+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.073 seconds
[2024-01-04T20:25:31.149+0000] {processor.py:161} INFO - Started process (PID=3730) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:25:31.151+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:25:31.153+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:25:31.153+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:25:31.188+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:25:31.181+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:25:31.191+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:25:31.215+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.071 seconds
[2024-01-04T20:26:01.642+0000] {processor.py:161} INFO - Started process (PID=3788) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:26:01.643+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:26:01.645+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:26:01.644+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:26:01.670+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:26:01.664+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:26:01.671+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:26:01.694+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.056 seconds
[2024-01-04T20:26:32.091+0000] {processor.py:161} INFO - Started process (PID=3846) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:26:32.093+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:26:32.095+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:26:32.094+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:26:32.128+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:26:32.122+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:26:32.130+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:26:32.152+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.067 seconds
[2024-01-04T20:27:03.027+0000] {processor.py:161} INFO - Started process (PID=3904) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:27:03.028+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:27:03.029+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:27:03.029+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:27:03.054+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:27:03.048+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:27:03.055+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:27:03.077+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.054 seconds
[2024-01-04T20:27:33.305+0000] {processor.py:161} INFO - Started process (PID=3962) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:27:33.306+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:27:33.308+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:27:33.307+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:27:33.336+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:27:33.330+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:27:33.339+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:27:33.362+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.061 seconds
[2024-01-04T20:28:03.790+0000] {processor.py:161} INFO - Started process (PID=4020) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:28:03.792+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:28:03.794+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:28:03.794+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:28:03.825+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:28:03.819+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:28:03.827+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:28:03.856+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.074 seconds
[2024-01-04T20:28:33.988+0000] {processor.py:161} INFO - Started process (PID=4078) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:28:33.990+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:28:33.991+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:28:33.991+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:28:34.027+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:28:34.020+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:28:34.029+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:28:34.062+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.081 seconds
[2024-01-04T20:29:04.427+0000] {processor.py:161} INFO - Started process (PID=4136) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:29:04.428+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:29:04.430+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:29:04.430+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:29:04.462+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:29:04.456+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:29:04.464+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:29:04.490+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.068 seconds
[2024-01-04T20:29:34.795+0000] {processor.py:161} INFO - Started process (PID=4194) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:29:34.797+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:29:34.798+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:29:34.798+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:29:34.830+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:29:34.823+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:29:34.832+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:29:34.861+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.069 seconds
[2024-01-04T20:30:05.109+0000] {processor.py:161} INFO - Started process (PID=4252) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:30:05.111+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:30:05.112+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:30:05.112+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:30:05.137+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:30:05.132+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:30:05.139+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:30:05.163+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.058 seconds
[2024-01-04T20:30:35.314+0000] {processor.py:161} INFO - Started process (PID=4310) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:30:35.315+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:30:35.316+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:30:35.316+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:30:35.343+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:30:35.337+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:30:35.345+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:30:35.433+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.123 seconds
[2024-01-04T20:31:06.237+0000] {processor.py:161} INFO - Started process (PID=4368) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:31:06.239+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:31:06.241+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:31:06.240+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:31:06.265+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:31:06.260+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:31:06.267+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:31:06.298+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.064 seconds
[2024-01-04T20:31:37.032+0000] {processor.py:161} INFO - Started process (PID=4426) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:31:37.033+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:31:37.034+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:31:37.034+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:31:37.064+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:31:37.057+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:31:37.066+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:31:37.096+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.068 seconds
[2024-01-04T20:32:07.190+0000] {processor.py:161} INFO - Started process (PID=4484) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:32:07.191+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:32:07.193+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:32:07.192+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:32:07.221+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:32:07.215+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:32:07.223+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:32:07.244+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.058 seconds
[2024-01-04T20:32:37.399+0000] {processor.py:161} INFO - Started process (PID=4542) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:32:37.401+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:32:37.402+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:32:37.402+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:32:37.431+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:32:37.425+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:32:37.433+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:32:37.465+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.070 seconds
[2024-01-04T20:33:08.032+0000] {processor.py:161} INFO - Started process (PID=4600) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:33:08.033+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:33:08.035+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:33:08.034+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:33:08.072+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:33:08.061+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:33:08.074+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:33:08.160+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.132 seconds
[2024-01-04T20:33:38.235+0000] {processor.py:161} INFO - Started process (PID=4658) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:33:38.236+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:33:38.238+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:33:38.237+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:33:38.266+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:33:38.260+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:33:38.267+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:33:38.298+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.068 seconds
[2024-01-04T20:34:08.408+0000] {processor.py:161} INFO - Started process (PID=4716) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:34:08.409+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:34:08.410+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:34:08.410+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:34:08.443+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:34:08.438+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:34:08.444+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:34:08.474+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.068 seconds
[2024-01-04T20:34:38.688+0000] {processor.py:161} INFO - Started process (PID=4774) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:34:38.689+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:34:38.691+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:34:38.691+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:34:38.723+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:34:38.717+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:34:38.726+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:34:38.754+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.071 seconds
[2024-01-04T20:35:09.322+0000] {processor.py:161} INFO - Started process (PID=4832) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:35:09.323+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:35:09.325+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:35:09.324+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:35:09.358+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:35:09.352+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:35:09.360+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:35:09.392+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.075 seconds
[2024-01-04T20:35:40.102+0000] {processor.py:161} INFO - Started process (PID=4890) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:35:40.104+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:35:40.105+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:35:40.105+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:35:40.137+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:35:40.129+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:35:40.139+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:35:40.164+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.067 seconds
[2024-01-04T20:36:10.774+0000] {processor.py:161} INFO - Started process (PID=4948) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:36:10.775+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:36:10.776+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:36:10.776+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:36:10.804+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:36:10.797+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:36:10.807+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:36:10.835+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.066 seconds
[2024-01-04T20:36:41.495+0000] {processor.py:161} INFO - Started process (PID=5006) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:36:41.496+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:36:41.498+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:36:41.497+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:36:41.527+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:36:41.521+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:36:41.529+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:36:41.557+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.067 seconds
[2024-01-04T20:37:12.182+0000] {processor.py:161} INFO - Started process (PID=5064) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:37:12.184+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:37:12.185+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:37:12.185+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:37:12.215+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:37:12.209+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:37:12.216+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:37:12.247+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.068 seconds
[2024-01-04T20:37:42.897+0000] {processor.py:161} INFO - Started process (PID=5122) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:37:42.899+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:37:42.900+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:37:42.900+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:37:42.927+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:37:42.921+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:37:42.929+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:37:42.957+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.066 seconds
[2024-01-04T20:38:13.373+0000] {processor.py:161} INFO - Started process (PID=5180) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:38:13.375+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:38:13.376+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:38:13.376+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:38:13.408+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:38:13.400+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:38:13.411+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:38:13.440+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.072 seconds
[2024-01-04T20:38:43.635+0000] {processor.py:161} INFO - Started process (PID=5238) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:38:43.637+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:38:43.639+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:38:43.638+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:38:43.690+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:38:43.682+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:38:43.692+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:38:43.730+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.102 seconds
[2024-01-04T20:39:14.426+0000] {processor.py:161} INFO - Started process (PID=5296) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:39:14.428+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:39:14.429+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:39:14.429+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:39:14.460+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:39:14.453+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:39:14.462+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:39:14.494+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.072 seconds
[2024-01-04T20:39:45.420+0000] {processor.py:161} INFO - Started process (PID=5355) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:39:45.422+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:39:45.425+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:39:45.424+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:39:45.473+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:39:45.466+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:39:45.481+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:39:45.516+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.112 seconds
[2024-01-04T20:40:16.195+0000] {processor.py:161} INFO - Started process (PID=5413) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:40:16.197+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:40:16.198+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:40:16.198+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:40:16.227+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:40:16.219+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:40:16.229+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:40:16.299+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.109 seconds
[2024-01-04T20:40:47.123+0000] {processor.py:161} INFO - Started process (PID=5471) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:40:47.125+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:40:47.127+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:40:47.126+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:40:47.169+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:40:47.161+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:40:47.172+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:40:47.201+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.082 seconds
[2024-01-04T20:41:17.351+0000] {processor.py:161} INFO - Started process (PID=5529) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:41:17.353+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:41:17.355+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:41:17.354+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:41:17.386+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:41:17.380+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:41:17.388+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:41:17.421+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.077 seconds
[2024-01-04T20:41:47.563+0000] {processor.py:161} INFO - Started process (PID=5587) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:41:47.565+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:41:47.568+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:41:47.567+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:41:47.600+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:41:47.594+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:41:47.604+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:41:47.642+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.084 seconds
[2024-01-04T20:42:17.761+0000] {processor.py:161} INFO - Started process (PID=5645) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:42:17.763+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:42:17.765+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:42:17.764+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:42:17.795+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:42:17.789+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:42:17.797+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:42:17.830+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.073 seconds
[2024-01-04T20:42:48.369+0000] {processor.py:161} INFO - Started process (PID=5703) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:42:48.373+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:42:48.375+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:42:48.374+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:42:48.408+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:42:48.401+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:42:48.410+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:42:48.440+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.077 seconds
[2024-01-04T20:43:18.958+0000] {processor.py:161} INFO - Started process (PID=5761) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:43:18.960+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:43:18.962+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:43:18.961+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:43:19.003+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:43:18.995+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:43:19.005+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:43:19.041+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.089 seconds
[2024-01-04T20:43:49.965+0000] {processor.py:161} INFO - Started process (PID=5819) to work on /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:43:49.967+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/sensor_dag.py for tasks to queue
[2024-01-04T20:43:49.968+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:43:49.968+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:43:49.996+0000] {logging_mixin.py:188} INFO - [2024-01-04T20:43:49.990+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/sensor_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/sensor_dag.py", line 13, in <module>
    waiting_for_file = FileSensor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 420, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'filepath'
[2024-01-04T20:43:49.998+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/sensor_dag.py
[2024-01-04T20:43:50.028+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/sensor_dag.py took 0.067 seconds
