[2023-12-28T04:27:03.004+0000] {processor.py:161} INFO - Started process (PID=41123) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:27:03.007+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:27:03.009+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:27:03.008+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:27:03.068+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:27:03.048+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 7
    catchup=False) as dag:
                         ^
SyntaxError: unexpected EOF while parsing
[2023-12-28T04:27:03.070+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:27:03.939+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.943 seconds
[2023-12-28T04:27:34.395+0000] {processor.py:161} INFO - Started process (PID=41179) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:27:34.397+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:27:34.398+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:27:34.398+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:27:34.416+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:27:34.414+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 7
    catchup=False) as dag:
                         ^
SyntaxError: unexpected EOF while parsing
[2023-12-28T04:27:34.417+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:27:34.447+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.056 seconds
[2023-12-28T04:28:05.025+0000] {processor.py:161} INFO - Started process (PID=41235) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:28:05.030+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:28:05.032+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:28:05.031+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:28:05.077+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:28:05.075+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 7
    catchup=False) as dag:
                         ^
SyntaxError: unexpected EOF while parsing
[2023-12-28T04:28:05.078+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:28:05.285+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.265 seconds
[2023-12-28T04:28:35.402+0000] {processor.py:161} INFO - Started process (PID=41291) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:28:35.405+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:28:35.408+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:28:35.407+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:28:35.444+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:28:35.441+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 7
    catchup=False) as dag:
                         ^
SyntaxError: unexpected EOF while parsing
[2023-12-28T04:28:35.446+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:28:35.494+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.096 seconds
[2023-12-28T04:29:08.661+0000] {processor.py:161} INFO - Started process (PID=41330) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:29:08.665+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:29:08.667+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:29:08.667+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:29:08.698+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:29:08.695+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 7
    catchup=False) as dag:
                         ^
SyntaxError: unexpected EOF while parsing
[2023-12-28T04:29:08.699+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:29:08.849+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.196 seconds
[2023-12-28T04:29:39.061+0000] {processor.py:161} INFO - Started process (PID=41387) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:29:39.092+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:29:39.095+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:29:39.095+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:29:39.189+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:29:39.186+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 7
    catchup=False) as dag:
                         ^
SyntaxError: unexpected EOF while parsing
[2023-12-28T04:29:39.190+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:29:39.458+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.405 seconds
[2023-12-28T04:30:09.516+0000] {processor.py:161} INFO - Started process (PID=41443) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:30:09.539+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:30:09.541+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:30:09.541+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:30:09.580+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:30:09.573+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 7
    catchup=False) as dag:
                         ^
SyntaxError: unexpected EOF while parsing
[2023-12-28T04:30:09.581+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:30:09.642+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.132 seconds
[2023-12-28T04:30:39.912+0000] {processor.py:161} INFO - Started process (PID=41496) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:30:39.925+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:30:39.926+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:30:39.926+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:30:40.033+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:30:40.010+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 7
    catchup=False) as dag:
                         ^
SyntaxError: unexpected EOF while parsing
[2023-12-28T04:30:40.035+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:30:40.256+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.348 seconds
[2023-12-28T04:31:11.130+0000] {processor.py:161} INFO - Started process (PID=41552) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:31:11.133+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:31:11.135+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:31:11.134+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:31:11.162+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:31:11.160+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 7
    catchup=False) as dag:
                         ^
SyntaxError: unexpected EOF while parsing
[2023-12-28T04:31:11.163+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:31:11.201+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.078 seconds
[2023-12-28T04:31:41.249+0000] {processor.py:161} INFO - Started process (PID=41608) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:31:41.251+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:31:41.253+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:31:41.252+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:31:41.271+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:31:41.270+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 7
    catchup=False) as dag:
                         ^
SyntaxError: unexpected EOF while parsing
[2023-12-28T04:31:41.272+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:31:41.299+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.055 seconds
[2023-12-28T04:32:11.429+0000] {processor.py:161} INFO - Started process (PID=41663) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:32:11.432+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:32:11.435+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:32:11.434+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:32:11.465+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:32:11.463+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 7
    catchup=False) as dag:
                         ^
SyntaxError: unexpected EOF while parsing
[2023-12-28T04:32:11.466+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:32:11.522+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.099 seconds
[2023-12-28T04:32:41.837+0000] {processor.py:161} INFO - Started process (PID=41719) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:32:41.854+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:32:41.857+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:32:41.856+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:32:42.869+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:32:41.961+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 7
    catchup=False) as dag:
                         ^
SyntaxError: unexpected EOF while parsing
[2023-12-28T04:32:42.874+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:32:42.943+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.122 seconds
[2023-12-28T04:33:13.343+0000] {processor.py:161} INFO - Started process (PID=41769) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:33:13.366+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:33:13.368+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:33:13.367+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:33:13.415+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:33:13.400+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 7
    catchup=False) as dag:
                         ^
SyntaxError: unexpected EOF while parsing
[2023-12-28T04:33:13.416+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:33:13.524+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.185 seconds
[2023-12-28T04:33:44.567+0000] {processor.py:161} INFO - Started process (PID=41821) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:33:44.580+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:33:44.584+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:33:44.583+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:33:44.662+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:33:44.660+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 7
    catchup=False) as dag:
                         ^
SyntaxError: unexpected EOF while parsing
[2023-12-28T04:33:44.664+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:33:44.840+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.281 seconds
[2023-12-28T04:34:15.152+0000] {processor.py:161} INFO - Started process (PID=41875) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:34:15.168+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:34:15.169+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:34:15.169+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:34:15.231+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:34:15.220+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 7
    catchup=False) as dag:
                         ^
SyntaxError: unexpected EOF while parsing
[2023-12-28T04:34:15.232+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:34:15.541+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.395 seconds
[2023-12-28T04:34:48.778+0000] {processor.py:161} INFO - Started process (PID=41931) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:34:48.780+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:34:48.782+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:34:48.781+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:34:49.079+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:34:48.815+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 7
    catchup=False) as dag:
                         ^
SyntaxError: unexpected EOF while parsing
[2023-12-28T04:34:49.080+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:34:49.407+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.639 seconds
[2023-12-28T04:35:19.894+0000] {processor.py:161} INFO - Started process (PID=41987) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:35:19.897+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:35:19.899+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:35:19.898+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:35:19.923+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:35:19.920+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 7
    catchup=False) as dag:
                         ^
SyntaxError: unexpected EOF while parsing
[2023-12-28T04:35:19.924+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:35:19.961+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.073 seconds
[2023-12-28T04:35:32.156+0000] {processor.py:161} INFO - Started process (PID=42023) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:35:32.157+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:35:32.159+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:35:32.159+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:35:32.205+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:35:32.198+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:35:32.207+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:35:32.244+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.094 seconds
[2023-12-28T04:36:02.795+0000] {processor.py:161} INFO - Started process (PID=42072) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:36:02.806+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:36:02.809+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:36:02.808+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:36:03.383+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:36:02.862+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:36:03.401+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:36:03.513+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.731 seconds
[2023-12-28T04:36:05.257+0000] {processor.py:161} INFO - Started process (PID=42079) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:36:05.260+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:36:05.264+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:36:05.262+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:36:05.342+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:36:05.332+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:36:05.345+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:36:05.400+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.153 seconds
[2023-12-28T04:36:35.968+0000] {processor.py:161} INFO - Started process (PID=42128) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:36:36.007+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:36:36.009+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:36:36.008+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:36:36.159+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:36:36.080+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:36:36.164+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:36:36.315+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.354 seconds
[2023-12-28T04:37:16.236+0000] {processor.py:161} INFO - Started process (PID=42161) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:37:16.242+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:37:16.247+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:37:16.246+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:37:16.391+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:37:16.289+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:37:16.410+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:37:16.929+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.701 seconds
[2023-12-28T04:37:47.324+0000] {processor.py:161} INFO - Started process (PID=42218) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:37:47.326+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:37:47.327+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:37:47.327+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:37:47.382+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:37:47.369+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:37:47.385+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:37:47.422+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.103 seconds
[2023-12-28T04:38:18.132+0000] {processor.py:161} INFO - Started process (PID=42274) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:38:18.142+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:38:18.144+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:38:18.144+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:38:18.211+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:38:18.202+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:38:18.213+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:38:18.253+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.125 seconds
[2023-12-28T04:38:28.384+0000] {processor.py:161} INFO - Started process (PID=42287) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:38:28.385+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:38:28.386+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:38:28.386+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:38:28.422+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:38:28.418+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:38:28.424+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:38:28.452+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.072 seconds
[2023-12-28T04:38:47.683+0000] {processor.py:161} INFO - Started process (PID=42324) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:38:47.685+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:38:47.687+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:38:47.686+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:38:47.744+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:38:47.737+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:38:47.748+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:38:47.796+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.120 seconds
[2023-12-28T04:39:18.737+0000] {processor.py:161} INFO - Started process (PID=42380) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:39:18.739+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:39:18.742+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:39:18.740+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:39:18.807+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:39:18.792+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:39:18.811+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:39:18.856+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.124 seconds
[2023-12-28T04:39:49.000+0000] {processor.py:161} INFO - Started process (PID=42436) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:39:49.001+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:39:49.003+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:39:49.002+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:39:49.053+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:39:49.046+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:39:49.055+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:39:49.148+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.151 seconds
[2023-12-28T04:40:20.154+0000] {processor.py:161} INFO - Started process (PID=42492) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:40:20.159+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:40:20.160+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:40:20.160+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:40:20.317+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:40:20.299+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:40:20.333+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:40:20.467+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.318 seconds
[2023-12-28T04:40:47.328+0000] {processor.py:161} INFO - Started process (PID=42538) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:40:47.329+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:40:47.331+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:40:47.330+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:40:47.451+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:40:47.439+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:40:47.454+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:40:47.610+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.286 seconds
[2023-12-28T04:41:20.786+0000] {processor.py:161} INFO - Started process (PID=42594) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:41:20.821+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:41:20.826+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:41:20.825+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:41:21.925+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:41:21.812+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:41:21.949+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:41:22.048+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.271 seconds
[2023-12-28T04:42:00.955+0000] {processor.py:161} INFO - Started process (PID=42647) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:42:01.019+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:42:01.021+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:42:01.020+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:42:02.564+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:42:02.221+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:42:02.567+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:42:02.677+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.727 seconds
[2023-12-28T04:42:40.334+0000] {processor.py:161} INFO - Started process (PID=42701) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:42:40.336+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:42:40.339+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:42:40.338+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:42:40.518+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:42:40.494+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:42:40.522+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:42:40.597+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.271 seconds
[2023-12-28T04:43:11.610+0000] {processor.py:161} INFO - Started process (PID=42756) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:43:11.612+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:43:11.616+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:43:11.615+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:43:11.647+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:43:11.640+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:43:11.649+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:43:11.686+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.084 seconds
[2023-12-28T04:43:42.633+0000] {processor.py:161} INFO - Started process (PID=42812) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:43:42.634+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:43:42.639+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:43:42.639+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:43:42.708+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:43:42.693+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:43:42.711+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:43:42.821+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.194 seconds
[2023-12-28T04:44:13.337+0000] {processor.py:161} INFO - Started process (PID=42868) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:44:13.339+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:44:13.347+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:44:13.346+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:44:13.395+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:44:13.387+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:44:13.398+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:44:13.444+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.118 seconds
[2023-12-28T04:44:44.232+0000] {processor.py:161} INFO - Started process (PID=42924) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:44:44.233+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:44:44.235+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:44:44.235+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:44:44.272+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:44:44.265+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:44:44.274+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:44:44.305+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.079 seconds
[2023-12-28T04:45:15.677+0000] {processor.py:161} INFO - Started process (PID=42976) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:45:15.704+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:45:15.706+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:45:15.706+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:45:15.878+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:45:15.841+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:45:15.880+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:45:16.421+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.749 seconds
[2023-12-28T04:45:46.670+0000] {processor.py:161} INFO - Started process (PID=43032) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:45:46.689+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:45:46.692+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:45:46.691+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:45:46.818+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:45:46.774+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:45:46.821+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:45:47.029+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.363 seconds
[2023-12-28T04:46:17.726+0000] {processor.py:161} INFO - Started process (PID=43088) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:46:17.728+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:46:17.730+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:46:17.729+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:46:17.777+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:46:17.771+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:46:17.780+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:46:17.816+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.098 seconds
[2023-12-28T04:46:48.243+0000] {processor.py:161} INFO - Started process (PID=43144) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:46:48.245+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:46:48.247+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:46:48.247+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:46:48.294+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:46:48.286+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:46:48.298+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:46:48.327+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.089 seconds
[2023-12-28T04:47:18.534+0000] {processor.py:161} INFO - Started process (PID=43200) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:47:18.535+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:47:18.537+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:47:18.536+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:47:18.579+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:47:18.573+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:47:18.581+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:47:18.616+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.087 seconds
[2023-12-28T04:47:49.071+0000] {processor.py:161} INFO - Started process (PID=43256) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:47:49.072+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:47:49.074+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:47:49.074+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:47:49.113+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:47:49.106+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:47:49.116+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:47:49.150+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.086 seconds
[2023-12-28T04:48:19.709+0000] {processor.py:161} INFO - Started process (PID=43312) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:48:19.710+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:48:19.712+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:48:19.711+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:48:19.745+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:48:19.739+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:48:19.749+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:48:19.782+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.078 seconds
[2023-12-28T04:48:50.248+0000] {processor.py:161} INFO - Started process (PID=43368) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:48:50.249+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:48:50.251+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:48:50.251+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:48:50.297+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:48:50.290+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:48:50.299+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:48:50.329+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.087 seconds
[2023-12-28T04:49:20.623+0000] {processor.py:161} INFO - Started process (PID=43424) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:49:20.626+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:49:20.629+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:49:20.628+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:49:20.668+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:49:20.662+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:49:20.670+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:49:20.702+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.085 seconds
[2023-12-28T04:49:50.913+0000] {processor.py:161} INFO - Started process (PID=43480) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:49:50.919+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:49:50.920+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:49:50.920+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:49:50.982+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:49:50.976+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:49:50.984+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:49:51.040+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.131 seconds
[2023-12-28T04:50:21.268+0000] {processor.py:161} INFO - Started process (PID=43536) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:50:21.269+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:50:21.271+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:50:21.270+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:50:21.307+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:50:21.300+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:50:21.309+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:50:21.345+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.081 seconds
[2023-12-28T04:50:51.738+0000] {processor.py:161} INFO - Started process (PID=43592) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:50:51.739+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:50:51.741+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:50:51.740+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:50:51.769+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:50:51.764+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:50:51.771+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:50:51.800+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.066 seconds
[2023-12-28T04:51:22.104+0000] {processor.py:161} INFO - Started process (PID=43648) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:51:22.106+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:51:22.107+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:51:22.107+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:51:22.133+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:51:22.128+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:51:22.136+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:51:22.181+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.081 seconds
[2023-12-28T04:51:52.611+0000] {processor.py:161} INFO - Started process (PID=43704) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:51:52.613+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:51:52.614+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:51:52.614+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:51:52.646+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:51:52.640+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:51:52.648+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:51:52.683+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.078 seconds
[2023-12-28T04:52:23.640+0000] {processor.py:161} INFO - Started process (PID=43760) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:52:23.642+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:52:23.644+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:52:23.643+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:52:23.686+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:52:23.679+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:52:23.689+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:52:23.739+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.105 seconds
[2023-12-28T04:52:53.903+0000] {processor.py:161} INFO - Started process (PID=43816) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:52:53.905+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:52:53.906+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:52:53.906+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:52:53.941+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:52:53.935+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:52:53.943+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:52:53.974+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.076 seconds
[2023-12-28T04:53:24.460+0000] {processor.py:161} INFO - Started process (PID=43872) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:53:24.461+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:53:24.463+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:53:24.463+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:53:24.498+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:53:24.491+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:53:24.500+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:53:24.534+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.079 seconds
[2023-12-28T04:53:55.059+0000] {processor.py:161} INFO - Started process (PID=43928) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:53:55.061+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:53:55.064+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:53:55.063+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:53:55.106+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:53:55.100+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:53:55.109+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:53:55.142+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.090 seconds
[2023-12-28T04:54:25.454+0000] {processor.py:161} INFO - Started process (PID=43984) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:54:25.456+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:54:25.459+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:54:25.457+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:54:25.497+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:54:25.490+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:54:25.500+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:54:25.539+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.091 seconds
[2023-12-28T04:54:56.147+0000] {processor.py:161} INFO - Started process (PID=44040) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:54:56.149+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:54:56.152+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:54:56.151+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:54:56.192+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:54:56.185+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:54:56.194+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:54:56.226+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.087 seconds
[2023-12-28T04:55:26.762+0000] {processor.py:161} INFO - Started process (PID=44096) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:55:26.764+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:55:26.765+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:55:26.765+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:55:26.802+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:55:26.795+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:55:26.805+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:55:26.833+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.076 seconds
[2023-12-28T04:55:57.263+0000] {processor.py:161} INFO - Started process (PID=44152) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:55:57.266+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:55:57.267+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:55:57.267+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:55:57.309+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:55:57.302+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:55:57.311+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:55:57.342+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.085 seconds
[2023-12-28T04:56:27.786+0000] {processor.py:161} INFO - Started process (PID=44208) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:56:27.787+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:56:27.789+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:56:27.788+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:56:27.821+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:56:27.815+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:56:27.823+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:56:27.854+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.076 seconds
[2023-12-28T04:56:58.337+0000] {processor.py:161} INFO - Started process (PID=44264) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:56:58.338+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:56:58.340+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:56:58.340+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:56:58.376+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:56:58.370+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:56:58.378+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:56:58.418+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.086 seconds
[2023-12-28T04:57:28.873+0000] {processor.py:161} INFO - Started process (PID=44320) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:57:28.874+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:57:28.876+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:57:28.876+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:57:28.909+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:57:28.901+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:57:28.912+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:57:28.942+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.074 seconds
[2023-12-28T04:57:59.322+0000] {processor.py:161} INFO - Started process (PID=44376) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:57:59.324+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:57:59.326+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:57:59.325+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:57:59.374+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:57:59.369+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:57:59.376+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:57:59.410+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.094 seconds
[2023-12-28T04:58:30.157+0000] {processor.py:161} INFO - Started process (PID=44432) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:58:30.159+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:58:30.161+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:58:30.160+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:58:30.193+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:58:30.188+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:58:30.195+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:58:30.219+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.068 seconds
[2023-12-28T04:59:00.618+0000] {processor.py:161} INFO - Started process (PID=44488) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:59:00.619+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:59:00.621+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:59:00.620+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:59:00.651+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:59:00.645+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:59:00.653+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:59:00.687+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.075 seconds
[2023-12-28T04:59:31.116+0000] {processor.py:161} INFO - Started process (PID=44544) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:59:31.117+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:59:31.119+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:59:31.119+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:59:31.159+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:59:31.152+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:59:31.161+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:59:31.197+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.086 seconds
[2023-12-28T05:00:01.689+0000] {processor.py:161} INFO - Started process (PID=44600) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:00:01.691+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:00:01.692+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:00:01.692+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:00:01.722+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:00:01.716+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T05:00:01.724+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:00:01.754+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.070 seconds
[2023-12-28T05:00:32.596+0000] {processor.py:161} INFO - Started process (PID=44656) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:00:32.598+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:00:32.599+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:00:32.599+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:00:32.631+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:00:32.622+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T05:00:32.633+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:00:32.809+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.218 seconds
[2023-12-28T05:01:02.964+0000] {processor.py:161} INFO - Started process (PID=44712) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:01:02.966+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:01:02.968+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:01:02.967+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:01:03.007+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:01:02.999+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T05:01:03.009+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:01:03.043+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.088 seconds
[2023-12-28T05:01:33.121+0000] {processor.py:161} INFO - Started process (PID=44768) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:01:33.123+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:01:33.125+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:01:33.124+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:01:33.161+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:01:33.154+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T05:01:33.163+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:01:33.189+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.072 seconds
[2023-12-28T05:02:03.785+0000] {processor.py:161} INFO - Started process (PID=44824) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:02:03.787+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:02:03.789+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:02:03.788+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:02:03.818+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:02:03.812+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T05:02:03.820+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:02:03.848+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.070 seconds
[2023-12-28T05:02:34.206+0000] {processor.py:161} INFO - Started process (PID=44880) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:02:34.207+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:02:34.210+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:02:34.209+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:02:34.238+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:02:34.232+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T05:02:34.241+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:02:34.273+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.071 seconds
[2023-12-28T05:03:04.761+0000] {processor.py:161} INFO - Started process (PID=44936) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:03:04.763+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:03:04.764+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:03:04.764+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:03:04.797+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:03:04.791+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T05:03:04.799+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:03:04.828+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.072 seconds
[2023-12-28T05:03:35.409+0000] {processor.py:161} INFO - Started process (PID=44992) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:03:35.412+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:03:35.414+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:03:35.413+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:03:35.456+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:03:35.446+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T05:03:35.461+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:03:35.495+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.094 seconds
[2023-12-28T05:04:06.174+0000] {processor.py:161} INFO - Started process (PID=45054) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:04:06.176+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:04:06.177+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:04:06.177+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:04:06.207+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:04:06.201+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T05:04:06.210+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:04:06.241+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.072 seconds
[2023-12-28T05:04:36.975+0000] {processor.py:161} INFO - Started process (PID=45110) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:04:36.976+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:04:36.979+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:04:36.978+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:04:37.008+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:04:37.003+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T05:04:37.011+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:04:37.049+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.103 seconds
[2023-12-28T05:05:07.580+0000] {processor.py:161} INFO - Started process (PID=45166) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:05:07.581+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:05:07.584+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:05:07.583+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:05:07.618+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:05:07.611+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T05:05:07.621+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:05:07.660+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.086 seconds
[2023-12-28T05:05:37.945+0000] {processor.py:161} INFO - Started process (PID=45222) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:05:37.947+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:05:37.948+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:05:37.948+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:05:37.985+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:05:37.979+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T05:05:37.987+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:05:38.022+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.082 seconds
[2023-12-28T05:06:08.389+0000] {processor.py:161} INFO - Started process (PID=45278) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:06:08.391+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:06:08.393+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:06:08.392+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:06:08.436+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:06:08.428+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T05:06:08.438+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:06:08.469+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.086 seconds
[2023-12-28T05:06:39.080+0000] {processor.py:161} INFO - Started process (PID=45334) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:06:39.082+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:06:39.083+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:06:39.083+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:06:39.111+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:06:39.106+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T05:06:39.114+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:06:39.144+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.069 seconds
[2023-12-28T05:07:09.775+0000] {processor.py:161} INFO - Started process (PID=45390) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:07:09.776+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:07:09.778+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:07:09.777+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:07:09.821+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:07:09.812+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T05:07:09.824+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:07:09.860+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.090 seconds
[2023-12-28T05:07:40.245+0000] {processor.py:161} INFO - Started process (PID=45446) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:07:40.247+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:07:40.249+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:07:40.248+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:07:40.292+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:07:40.285+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T05:07:40.295+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:07:40.330+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.092 seconds
[2023-12-28T05:08:10.765+0000] {processor.py:161} INFO - Started process (PID=45502) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:08:10.767+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:08:10.770+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:08:10.769+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:08:10.807+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:08:10.799+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T05:08:10.809+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:08:10.841+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.082 seconds
[2023-12-28T05:08:41.605+0000] {processor.py:161} INFO - Started process (PID=45558) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:08:41.607+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:08:41.608+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:08:41.608+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:08:41.642+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:08:41.636+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T05:08:41.645+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:08:41.677+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.079 seconds
[2023-12-28T05:09:11.899+0000] {processor.py:161} INFO - Started process (PID=45614) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:09:11.901+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:09:11.902+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:09:11.902+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:09:11.946+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:09:11.937+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T05:09:11.950+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:09:11.978+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.083 seconds
[2023-12-28T05:09:42.389+0000] {processor.py:161} INFO - Started process (PID=45670) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:09:42.391+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:09:42.393+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:09:42.392+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:09:42.425+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:09:42.419+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T05:09:42.428+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:09:42.464+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.079 seconds
[2023-12-28T05:10:12.605+0000] {processor.py:161} INFO - Started process (PID=45726) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:10:12.606+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:10:12.608+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:10:12.607+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:10:12.632+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:10:12.627+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T05:10:12.634+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:10:12.662+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.062 seconds
[2023-12-28T05:10:43.231+0000] {processor.py:161} INFO - Started process (PID=45782) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:10:43.233+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:10:43.235+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:10:43.235+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:10:43.279+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:10:43.269+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T05:10:43.283+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:10:43.325+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.102 seconds
[2023-12-28T05:11:13.958+0000] {processor.py:161} INFO - Started process (PID=45838) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:11:13.959+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:11:13.961+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:11:13.961+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:11:13.992+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:11:13.986+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T05:11:13.995+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:11:14.020+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.066 seconds
[2023-12-28T05:11:44.558+0000] {processor.py:161} INFO - Started process (PID=45894) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:11:44.561+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:11:44.564+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:11:44.563+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:11:44.609+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:11:44.601+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T05:11:44.612+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:11:44.643+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.091 seconds
[2023-12-28T05:11:57.596+0000] {processor.py:161} INFO - Started process (PID=45922) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:11:57.598+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:11:57.599+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:11:57.598+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:11:57.640+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:11:57.635+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T05:11:57.643+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:11:57.679+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.086 seconds
[2023-12-28T05:12:28.054+0000] {processor.py:161} INFO - Started process (PID=45978) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:12:28.056+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:12:28.058+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:12:28.058+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:12:28.105+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:12:28.093+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T05:12:28.107+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:12:30.147+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 2.099 seconds
[2023-12-28T05:13:00.407+0000] {processor.py:161} INFO - Started process (PID=46034) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:13:00.409+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:13:00.410+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:13:00.410+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:13:00.472+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:13:00.449+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T05:13:00.476+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:13:00.504+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.103 seconds
[2023-12-28T05:13:30.750+0000] {processor.py:161} INFO - Started process (PID=46090) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:13:30.751+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:13:30.753+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:13:30.752+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:13:30.786+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:13:30.780+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T05:13:30.789+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:13:30.825+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.080 seconds
[2023-12-28T05:14:01.108+0000] {processor.py:161} INFO - Started process (PID=46143) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:14:01.110+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:14:01.113+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:14:01.112+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:14:01.144+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:14:01.138+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T05:14:01.147+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:14:01.199+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.099 seconds
[2023-12-28T05:14:31.863+0000] {processor.py:161} INFO - Started process (PID=46199) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:14:31.865+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:14:31.869+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:14:31.868+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:14:31.908+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:14:31.901+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T05:14:31.910+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:14:31.947+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.089 seconds
[2023-12-28T05:15:02.120+0000] {processor.py:161} INFO - Started process (PID=46255) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:15:02.123+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:15:02.129+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:15:02.125+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:15:02.185+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:15:02.174+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T05:15:02.188+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:15:02.231+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.118 seconds
[2023-12-28T05:15:32.338+0000] {processor.py:161} INFO - Started process (PID=46311) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:15:32.340+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:15:32.342+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:15:32.341+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:15:32.397+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:15:32.389+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T05:15:32.400+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:15:32.451+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.123 seconds
[2023-12-28T05:16:03.392+0000] {processor.py:161} INFO - Started process (PID=46367) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:16:03.399+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:16:03.401+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:16:03.401+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:16:03.523+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:16:03.511+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T05:16:03.527+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:16:03.619+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.232 seconds
[2023-12-28T05:16:34.227+0000] {processor.py:161} INFO - Started process (PID=46423) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:16:34.229+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:16:34.232+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:16:34.231+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:16:34.281+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:16:34.274+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T05:16:34.284+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:16:34.389+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.167 seconds
[2023-12-28T05:17:05.584+0000] {processor.py:161} INFO - Started process (PID=46479) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:17:05.585+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:17:05.587+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:17:05.587+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:17:05.634+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:17:05.623+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T05:17:05.638+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:17:06.602+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.027 seconds
[2023-12-28T05:17:24.770+0000] {processor.py:161} INFO - Started process (PID=46508) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:17:24.783+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:17:24.787+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:17:24.786+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:17:24.895+0000] {processor.py:840} INFO - DAG(s) 'my_dag' retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:17:25.441+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:17:25.439+0000] {override.py:1769} INFO - Created Permission View: can read on DAG:my_dag
[2023-12-28T05:17:25.490+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:17:25.490+0000] {override.py:1769} INFO - Created Permission View: can delete on DAG:my_dag
[2023-12-28T05:17:25.529+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:17:25.528+0000] {override.py:1769} INFO - Created Permission View: can edit on DAG:my_dag
[2023-12-28T05:17:25.553+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:17:25.540+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2023-12-28T05:17:25.647+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:17:25.646+0000] {dag.py:3055} INFO - Creating ORM DAG for my_dag
[2023-12-28T05:17:25.717+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:17:25.717+0000] {dag.py:3820} INFO - Setting next_dagrun for my_dag to 2023-12-27T00:00:00+00:00, run_after=2023-12-28T00:00:00+00:00
[2023-12-28T05:17:25.929+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.170 seconds
[2023-12-28T05:17:56.072+0000] {processor.py:161} INFO - Started process (PID=46564) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:17:56.074+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:17:56.076+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:17:56.075+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:17:56.109+0000] {processor.py:840} INFO - DAG(s) 'my_dag' retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:17:56.145+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:17:56.145+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2023-12-28T05:17:56.189+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:17:56.189+0000] {dag.py:3820} INFO - Setting next_dagrun for my_dag to 2023-12-27T00:00:00+00:00, run_after=2023-12-28T00:00:00+00:00
[2023-12-28T05:17:56.228+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.161 seconds
[2023-12-28T05:18:26.685+0000] {processor.py:161} INFO - Started process (PID=46620) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:18:26.687+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:18:26.689+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:18:26.689+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:18:26.727+0000] {processor.py:840} INFO - DAG(s) 'my_dag' retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:18:26.757+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:18:26.756+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2023-12-28T05:18:26.787+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:18:26.786+0000] {dag.py:3820} INFO - Setting next_dagrun for my_dag to 2023-12-27T00:00:00+00:00, run_after=2023-12-28T00:00:00+00:00
[2023-12-28T05:18:26.813+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.135 seconds
[2023-12-28T05:18:57.568+0000] {processor.py:161} INFO - Started process (PID=46676) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:18:57.572+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:18:57.574+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:18:57.573+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:18:57.641+0000] {processor.py:840} INFO - DAG(s) 'my_dag' retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:18:57.705+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:18:57.705+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2023-12-28T05:18:57.768+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:18:57.767+0000] {dag.py:3820} INFO - Setting next_dagrun for my_dag to 2023-12-28T00:00:00+00:00, run_after=2023-12-29T00:00:00+00:00
[2023-12-28T05:18:57.818+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.262 seconds
[2023-12-28T05:19:28.137+0000] {processor.py:161} INFO - Started process (PID=46732) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:19:28.139+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:19:28.141+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:19:28.141+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:19:28.184+0000] {processor.py:840} INFO - DAG(s) 'my_dag' retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:19:28.219+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:19:28.219+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2023-12-28T05:19:28.258+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:19:28.258+0000] {dag.py:3820} INFO - Setting next_dagrun for my_dag to 2023-12-28T00:00:00+00:00, run_after=2023-12-29T00:00:00+00:00
[2023-12-28T05:19:28.295+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.166 seconds
[2023-12-28T05:19:58.615+0000] {processor.py:161} INFO - Started process (PID=46786) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:19:58.617+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:19:58.619+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:19:58.619+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:19:58.657+0000] {processor.py:840} INFO - DAG(s) 'my_dag' retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:19:58.693+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:19:58.692+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2023-12-28T05:19:58.727+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:19:58.727+0000] {dag.py:3820} INFO - Setting next_dagrun for my_dag to 2023-12-28T00:00:00+00:00, run_after=2023-12-29T00:00:00+00:00
[2023-12-28T05:19:58.891+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.284 seconds
[2023-12-28T05:20:29.087+0000] {processor.py:161} INFO - Started process (PID=46842) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:20:29.088+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:20:29.090+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:20:29.090+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:20:29.146+0000] {processor.py:840} INFO - DAG(s) 'my_dag' retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:20:29.185+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:20:29.185+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2023-12-28T05:20:29.223+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:20:29.222+0000] {dag.py:3820} INFO - Setting next_dagrun for my_dag to 2023-12-28T00:00:00+00:00, run_after=2023-12-29T00:00:00+00:00
[2023-12-28T05:20:29.270+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.189 seconds
[2023-12-28T05:20:59.515+0000] {processor.py:161} INFO - Started process (PID=46894) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:20:59.524+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:20:59.529+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:20:59.527+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:20:59.637+0000] {processor.py:840} INFO - DAG(s) 'my_dag' retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:20:59.760+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:20:59.759+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2023-12-28T05:20:59.807+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:20:59.806+0000] {dag.py:3820} INFO - Setting next_dagrun for my_dag to 2023-12-28T00:00:00+00:00, run_after=2023-12-29T00:00:00+00:00
[2023-12-28T05:20:59.838+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.372 seconds
[2023-12-28T05:21:30.182+0000] {processor.py:161} INFO - Started process (PID=46950) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:21:30.186+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:21:30.190+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:21:30.189+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:21:30.282+0000] {processor.py:840} INFO - DAG(s) 'my_dag' retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:21:30.439+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:21:30.439+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2023-12-28T05:21:30.541+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:21:30.540+0000] {dag.py:3820} INFO - Setting next_dagrun for my_dag to 2023-12-28T00:00:00+00:00, run_after=2023-12-29T00:00:00+00:00
[2023-12-28T05:21:30.620+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.445 seconds
[2023-12-28T05:22:01.608+0000] {processor.py:161} INFO - Started process (PID=47016) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:22:01.615+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:22:01.619+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:22:01.618+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:22:01.720+0000] {processor.py:840} INFO - DAG(s) 'my_dag' retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:22:01.882+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:22:01.881+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2023-12-28T05:22:02.077+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:22:02.076+0000] {dag.py:3820} INFO - Setting next_dagrun for my_dag to 2023-12-28T00:00:00+00:00, run_after=2023-12-29T00:00:00+00:00
[2023-12-28T05:22:02.228+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.660 seconds
[2023-12-28T05:22:53.161+0000] {processor.py:161} INFO - Started process (PID=47045) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:22:53.163+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:22:53.165+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:22:53.164+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:22:53.231+0000] {processor.py:840} INFO - DAG(s) 'my_dag' retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:22:53.291+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:22:53.291+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2023-12-28T05:22:53.335+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:22:53.335+0000] {dag.py:3820} INFO - Setting next_dagrun for my_dag to 2023-12-28T00:00:00+00:00, run_after=2023-12-29T00:00:00+00:00
[2023-12-28T05:22:53.373+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.216 seconds
[2023-12-28T05:23:23.458+0000] {processor.py:161} INFO - Started process (PID=47095) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:23:23.459+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:23:23.461+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:23:23.460+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:23:23.499+0000] {processor.py:840} INFO - DAG(s) 'my_dag' retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:23:23.528+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:23:23.527+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2023-12-28T05:23:23.562+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:23:23.561+0000] {dag.py:3820} INFO - Setting next_dagrun for my_dag to 2023-12-28T00:00:00+00:00, run_after=2023-12-29T00:00:00+00:00
[2023-12-28T05:23:23.596+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.143 seconds
[2023-12-28T05:23:54.188+0000] {processor.py:161} INFO - Started process (PID=47155) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:23:54.190+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:23:54.192+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:23:54.191+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:23:54.239+0000] {processor.py:840} INFO - DAG(s) 'my_dag' retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:23:54.267+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:23:54.267+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2023-12-28T05:23:54.302+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:23:54.301+0000] {dag.py:3820} INFO - Setting next_dagrun for my_dag to 2023-12-28T00:00:00+00:00, run_after=2023-12-29T00:00:00+00:00
[2023-12-28T05:23:54.336+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.153 seconds
[2023-12-28T05:24:24.871+0000] {processor.py:161} INFO - Started process (PID=47211) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:24:24.873+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:24:24.875+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:24:24.874+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:24:24.932+0000] {processor.py:840} INFO - DAG(s) 'my_dag' retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:24:24.962+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:24:24.961+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2023-12-28T05:24:24.989+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:24:24.989+0000] {dag.py:3820} INFO - Setting next_dagrun for my_dag to 2023-12-28T00:00:00+00:00, run_after=2023-12-29T00:00:00+00:00
[2023-12-28T05:24:25.189+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.323 seconds
[2023-12-28T05:24:55.268+0000] {processor.py:161} INFO - Started process (PID=47267) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:24:55.269+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:24:55.271+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:24:55.270+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:24:55.315+0000] {processor.py:840} INFO - DAG(s) 'my_dag' retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:24:55.340+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:24:55.340+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2023-12-28T05:24:55.370+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:24:55.370+0000] {dag.py:3820} INFO - Setting next_dagrun for my_dag to 2023-12-28T00:00:00+00:00, run_after=2023-12-29T00:00:00+00:00
[2023-12-28T05:24:55.407+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.144 seconds
[2023-12-28T05:25:25.564+0000] {processor.py:161} INFO - Started process (PID=47321) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:25:25.566+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:25:25.567+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:25:25.567+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:25:25.612+0000] {processor.py:840} INFO - DAG(s) 'my_dag' retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:25:25.642+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:25:25.642+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2023-12-28T05:25:25.678+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:25:25.677+0000] {dag.py:3820} INFO - Setting next_dagrun for my_dag to 2023-12-28T00:00:00+00:00, run_after=2023-12-29T00:00:00+00:00
[2023-12-28T05:25:25.738+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.178 seconds
[2023-12-28T05:25:55.848+0000] {processor.py:161} INFO - Started process (PID=47376) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:25:55.849+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:25:55.851+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:25:55.850+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:25:55.884+0000] {processor.py:840} INFO - DAG(s) 'my_dag' retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:25:55.918+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:25:55.918+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2023-12-28T05:25:55.961+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:25:55.961+0000] {dag.py:3820} INFO - Setting next_dagrun for my_dag to 2023-12-28T00:00:00+00:00, run_after=2023-12-29T00:00:00+00:00
[2023-12-28T05:25:55.998+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.156 seconds
[2023-12-28T05:26:26.352+0000] {processor.py:161} INFO - Started process (PID=47433) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:26:26.360+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:26:26.362+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:26:26.361+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:26:26.395+0000] {processor.py:840} INFO - DAG(s) 'my_dag' retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:26:26.418+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:26:26.418+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2023-12-28T05:26:26.452+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:26:26.451+0000] {dag.py:3820} INFO - Setting next_dagrun for my_dag to 2023-12-28T00:00:00+00:00, run_after=2023-12-29T00:00:00+00:00
[2023-12-28T05:26:26.483+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.135 seconds
[2023-12-28T05:27:21.312+0000] {processor.py:161} INFO - Started process (PID=47490) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:27:21.352+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:27:21.431+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:27:21.353+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:27:21.752+0000] {processor.py:840} INFO - DAG(s) 'my_dag' retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:27:32.700+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:27:32.700+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2023-12-28T05:27:33.414+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:27:33.413+0000] {dag.py:3820} INFO - Setting next_dagrun for my_dag to 2023-12-28T00:00:00+00:00, run_after=2023-12-29T00:00:00+00:00
[2023-12-28T05:27:33.867+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 12.668 seconds
[2023-12-28T05:28:12.897+0000] {processor.py:161} INFO - Started process (PID=47547) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:28:12.908+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:28:12.910+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:28:12.910+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:28:13.050+0000] {processor.py:840} INFO - DAG(s) 'my_dag' retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:28:13.082+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:28:13.082+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2023-12-28T05:28:13.118+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:28:13.117+0000] {dag.py:3820} INFO - Setting next_dagrun for my_dag to 2023-12-28T00:00:00+00:00, run_after=2023-12-29T00:00:00+00:00
[2023-12-28T05:28:13.223+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.332 seconds
[2023-12-28T05:28:43.525+0000] {processor.py:161} INFO - Started process (PID=47600) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:28:43.527+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:28:43.530+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:28:43.529+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:28:43.586+0000] {processor.py:840} INFO - DAG(s) 'my_dag' retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:28:43.635+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:28:43.634+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2023-12-28T05:28:43.704+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:28:43.704+0000] {dag.py:3820} INFO - Setting next_dagrun for my_dag to 2023-12-28T00:00:00+00:00, run_after=2023-12-29T00:00:00+00:00
[2023-12-28T05:28:43.779+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.261 seconds
[2023-12-28T05:29:14.168+0000] {processor.py:161} INFO - Started process (PID=47656) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:29:14.185+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:29:14.197+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:29:14.195+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T05:29:14.447+0000] {processor.py:840} INFO - DAG(s) 'my_dag' retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T05:29:14.981+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:29:14.981+0000] {dag.py:3033} INFO - Sync 1 DAGs
[2023-12-28T05:29:15.207+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:29:15.206+0000] {dag.py:3820} INFO - Setting next_dagrun for my_dag to 2023-12-28T00:00:00+00:00, run_after=2023-12-29T00:00:00+00:00
[2023-12-28T05:29:15.438+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.309 seconds
[2023-12-28T05:29:47.113+0000] {processor.py:161} INFO - Started process (PID=47711) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T05:29:47.369+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T05:29:48.724+0000] {logging_mixin.py:188} INFO - [2023-12-28T05:29:48.206+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
